spring.application.name=PlacementManagementSystem

# Host Name
HOST=${HOST}

# The allowed origin for WebSocket connections - the host name of the application
websocket.allowed-origin=${HOST}
# Scheduler cron expression for updating placements, every day at midnight
scheduler.update-placements.cron=0 0 0 * * *
# Scheduler cron expression for updating visits, every day at midnight
scheduler.update-visits.cron=0 0 0 * * *
# Scheduler cron expression for sending unread messages email reminder, every day at midday
scheduler.send-unread-messages-email.cron=0 0 12 * * *

# Debug logging statements
logging.level.web=debug
logging.level.org.hibernate.SQL=debug
logging.level.org.springframework.security=debug

# DB Spring JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MySQL DB - Localhost
#spring.datasource.url=${PMS_DB_URL}
#spring.datasource.username=${PMS_DB_USERNAME}
#spring.datasource.password=${PMS_DB_PASSWORD}

# MySQL DB - CleverCloud
spring.datasource.url=${PMS_DB_CLEVERCLOUD_URL}
spring.datasource.username=${PMS_DB_CLEVERCLOUD_USERNAME}
spring.datasource.password=${PMS_DB_CLEVERCLOUD_PASSWORD}
spring.datasource.hikari.maximum-pool-size=4

# Microsoft Graph API
spring.security.oauth2.client.registration.microsoft.client-id=${PMS_MICROSOFT_CLIENT_ID}
spring.security.oauth2.client.registration.microsoft.client-secret=${PMS_MICROSOFT_CLIENT_SECRET}
spring.security.oauth2.client.registration.microsoft.redirect-uri=${HOST}/tutor/visits/new/calendar-auth/callback
spring.security.oauth2.client.registration.microsoft.client-name=Microsoft
spring.security.oauth2.client.registration.microsoft.scope=User.Read,Calendars.ReadWrite
spring.security.oauth2.client.registration.microsoft.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.microsoft.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.microsoft.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.microsoft.user-info-uri=https://graph.microsoft.com/v1.0/me
spring.security.oauth2.client.provider.microsoft.user-name-attribute=id

# MailerSend API
mailersend.api-key=${PMS_MAILERSEND_API_KEY}
mailersend.from-email=${PMS_MAILERSEND_FROM_EMAIL}
mailersend.template.company-approval=${PMS_MAILERSEND_TEMPLATE_COMPANY_APPROVAL}
mailersend.template.reset-password=${PMS_MAILERSEND_TEMPLATE_RESET_PASSWORD}
mailersend.template.account-activation=${PMS_MAILERSEND_TEMPLATE_ACCOUNT_ACTIVATION}

# Google Gemini API
google.gemini.api-key=${PMS_GOOGLE_GEMINI_API_KEY}